<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AssemblyName>WiFile</AssemblyName>
    <RootNamespace>WiFile</RootNamespace>
    <ApplicationIcon>..\..\assets\WiFile.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>1.1.0</Version>
    <Product>WiFile</Product>
    <Company>WiFile</Company>
    <Description>WiFile - share files and chat with PCs on the same Wi-Fi</Description>
    <Copyright>MIT License</Copyright>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <DebugType>embedded</DebugType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.IO.Compression.FileSystem" />
    <Reference Include="Microsoft.VisualBasic" />
  </ItemGroup>
</Project>
