<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Prefer32Bit>false</Prefer32Bit>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\src\WiFile\Core\**\*.cs" Link="Core\%(RecursiveDir)%(Filename)%(Extension)" />
    <Reference Include="System.Web.Extensions" />
  </ItemGroup>
</Project>
